/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g.browser;

/**
 *
 * @author paolo
 */
public class BrowserGUI extends javax.swing.JFrame {
    private BrowserBL bl = new BrowserBL();
    private Cronologia cronologia = new Cronologia();
    /**
     * Creates new form BrowserGUI
     */
    public BrowserGUI() {
        initComponents();
        tastoAvanti.setEnabled(false);
        tastoIndietro.setEnabled(false);
        jTextPane1.setContentType("text/html");
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tastoIndietro = new javax.swing.JButton();
        tastoAvanti = new javax.swing.JButton();
        addressBar = new javax.swing.JTextField();
        tastoGo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tastoIndietro.setText("<<");
        tastoIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tastoIndietroActionPerformed(evt);
            }
        });

        tastoAvanti.setText(">>");
        tastoAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tastoAvantiActionPerformed(evt);
            }
        });

        tastoGo.setText("GO");
        tastoGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tastoGoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addressBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tastoGo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tastoIndietro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tastoAvanti)
                        .addGap(0, 674, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tastoIndietro)
                    .addComponent(tastoAvanti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tastoGo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tastoIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tastoIndietroActionPerformed
        // TODO add your handling code here:
        
        String url=cronologia.tornaIndietro();
        if ( url.isEmpty()) return; //non dovrebbe accadere 
        
        addressBar.setText(url);
        String pagina= bl.getPaginaFrom( url );
        jTextPane1.setText(pagina);
        
        cronologia.dump();
        
        if (cronologia.haUnPrecedessore())
            tastoIndietro.setEnabled(true);
        else
            tastoIndietro.setEnabled(false);
        
        if (cronologia.haUnSuccessore())
            tastoAvanti.setEnabled(true);
        else
            tastoAvanti.setEnabled(false);
        
    }//GEN-LAST:event_tastoIndietroActionPerformed

    private void tastoAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tastoAvantiActionPerformed
        // TODO add your handling code here:
        
        String url=cronologia.vaiAvanti();
        if ( url.isEmpty()) return; //non dovrebbe accadere 

        addressBar.setText(url);
        String pagina= bl.getPaginaFrom( url );
        jTextPane1.setText(pagina);
        
        cronologia.dump();
        
        if (cronologia.haUnPrecedessore())
            tastoIndietro.setEnabled(true);
        else
            tastoIndietro.setEnabled(false);
        
        if (cronologia.haUnSuccessore())
            tastoAvanti.setEnabled(true);
        else
            tastoAvanti.setEnabled(false);
    }//GEN-LAST:event_tastoAvantiActionPerformed

    private void tastoGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tastoGoActionPerformed
        // TODO add your handling code here:
        String url=addressBar.getText();
        if ( url.isEmpty()) return;
        
        String pagina= bl.getPaginaFrom( url );
        
        jTextPane1.setText(pagina);
        
        cronologia.aggiungiInCronologia(url);
        cronologia.dump();
        
        if (cronologia.haUnPrecedessore())
            tastoIndietro.setEnabled(true);
        else
            tastoIndietro.setEnabled(false);
        
        if (cronologia.haUnSuccessore())
            tastoAvanti.setEnabled(true);
        else
            tastoAvanti.setEnabled(false);
            
    }//GEN-LAST:event_tastoGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton tastoAvanti;
    private javax.swing.JButton tastoGo;
    private javax.swing.JButton tastoIndietro;
    // End of variables declaration//GEN-END:variables
}
